// Generated by gencpp from file edge_detection/edgeDetection.msg
// DO NOT EDIT!


#ifndef EDGE_DETECTION_MESSAGE_EDGEDETECTION_H
#define EDGE_DETECTION_MESSAGE_EDGEDETECTION_H

#include <ros/service_traits.h>


#include <edge_detection/edgeDetectionRequest.h>
#include <edge_detection/edgeDetectionResponse.h>


namespace edge_detection
{

struct edgeDetection
{

typedef edgeDetectionRequest Request;
typedef edgeDetectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct edgeDetection
} // namespace edge_detection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::edge_detection::edgeDetection > {
  static const char* value()
  {
    return "45cb70aa84739952753ff37531689216";
  }

  static const char* value(const ::edge_detection::edgeDetection&) { return value(); }
};

template<>
struct DataType< ::edge_detection::edgeDetection > {
  static const char* value()
  {
    return "edge_detection/edgeDetection";
  }

  static const char* value(const ::edge_detection::edgeDetection&) { return value(); }
};


// service_traits::MD5Sum< ::edge_detection::edgeDetectionRequest> should match
// service_traits::MD5Sum< ::edge_detection::edgeDetection >
template<>
struct MD5Sum< ::edge_detection::edgeDetectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::edge_detection::edgeDetection >::value();
  }
  static const char* value(const ::edge_detection::edgeDetectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::edge_detection::edgeDetectionRequest> should match
// service_traits::DataType< ::edge_detection::edgeDetection >
template<>
struct DataType< ::edge_detection::edgeDetectionRequest>
{
  static const char* value()
  {
    return DataType< ::edge_detection::edgeDetection >::value();
  }
  static const char* value(const ::edge_detection::edgeDetectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::edge_detection::edgeDetectionResponse> should match
// service_traits::MD5Sum< ::edge_detection::edgeDetection >
template<>
struct MD5Sum< ::edge_detection::edgeDetectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::edge_detection::edgeDetection >::value();
  }
  static const char* value(const ::edge_detection::edgeDetectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::edge_detection::edgeDetectionResponse> should match
// service_traits::DataType< ::edge_detection::edgeDetection >
template<>
struct DataType< ::edge_detection::edgeDetectionResponse>
{
  static const char* value()
  {
    return DataType< ::edge_detection::edgeDetection >::value();
  }
  static const char* value(const ::edge_detection::edgeDetectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EDGE_DETECTION_MESSAGE_EDGEDETECTION_H
