set(_CATKIN_CURRENT_PACKAGE "edge_detection")
set(edge_detection_VERSION "0.0.0")
set(edge_detection_MAINTAINER "atma <atma@todo.todo>")
set(edge_detection_PACKAGE_FORMAT "2")
set(edge_detection_BUILD_DEPENDS "message_generation" "geometry_msgs" "std_msgs" "sensor_msgs")
set(edge_detection_BUILD_EXPORT_DEPENDS "geometry_msgs" "std_msgs" "sensor_msgs")
set(edge_detection_BUILDTOOL_DEPENDS "catkin")
set(edge_detection_BUILDTOOL_EXPORT_DEPENDS )
set(edge_detection_EXEC_DEPENDS "message_runtime" "geometry_msgs" "std_msgs" "sensor_msgs")
set(edge_detection_RUN_DEPENDS "message_runtime" "geometry_msgs" "std_msgs" "sensor_msgs")
set(edge_detection_TEST_DEPENDS )
set(edge_detection_DOC_DEPENDS )
set(edge_detection_URL_WEBSITE "")
set(edge_detection_URL_BUGTRACKER "")
set(edge_detection_URL_REPOSITORY "")
set(edge_detection_DEPRECATED "")